version: "3"

services:

    government.agent.api.de4a.eu:
        container_name: ${AGENT_API_CONTAINER_NAME}
        image: ${AGENT_API_IMAGE}:${AGENT_API_IMAGE_TAG}
        ports:
            - 0.0.0.0:${AGENT_API_PORT}:8080
        volumes:
            - ./app.properties:/usr/local/tomcat/conf/app.properties
        networks:
            - agent_de4a_net

volumes:
    db_data: {}

networks:
    agent_de4a_net:
        external: true



