version: "3"

services:

    tomcat:
        container_name: de4a-tomcat
        image: tomcat:latest
        ports:
            - "127.0.0.1:8080:8080"

        volumes:
            - "./out/artifacts/de4a_agent:/usr/local/tomcat/webapps"
            - "./src/main/resources/app.properties:/usr/local/tomcat/conf/app.properties"
volumes:
    db_data: {}    